In [1]:
import pandas as pd

In [2]:
augustdf= pd.read_csv('August2022.csv')
augustdf.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,D68047AAA9A72501,classic_bike,8/12/2022 18:14,8/12/2022 18:21,Columbus Drive,JC014,Hamilton Park,JC009,40.718355,-74.038914,40.727596,-74.044247,member
1,E5B82A9F588A7650,classic_bike,8/19/2022 1:04,8/19/2022 1:14,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,8 St & Washington St,HB603,40.736982,-74.027781,40.745984,-74.028199,member
2,13D19CCBCC9D7B76,classic_bike,8/19/2022 18:13,8/19/2022 19:32,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member
3,AA0DBFF220DA98F6,classic_bike,8/21/2022 13:43,8/21/2022 13:53,Columbus Drive,JC014,Montgomery St,JC099,40.718355,-74.038914,40.719420,-74.050990,member
4,8F11D340492FCD32,electric_bike,8/4/2022 22:02,8/4/2022 22:21,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Pershing Field,JC024,40.736982,-74.027781,40.742677,-74.051789,member

In [6]:
total_df= pd.concat(map(pd.read_csv, ['July2022.csv', 'June2022.csv', 'August2022.csv', 'September2022.csv']), ignore_index= True)
print(total_df)

                 ride_id  rideable_type       started_at         ended_at  \
0       89CDCE3224502904   classic_bike  7/21/2022 18:19  7/21/2022 18:28
1       3E6E50F51BD4CBD9  electric_bike  7/21/2022 17:50  7/21/2022 17:59
2       8A9058FAA9115562  electric_bike  7/23/2022 11:51  7/23/2022 11:59
3       C566A187663748AE   classic_bike  7/30/2022 20:34  7/30/2022 20:48
4       7E754D57276BE57E   classic_bike  7/14/2022 18:42  7/14/2022 18:49
...                  ...            ...              ...              ...
431274  5DE7C59F63BA7E17   classic_bike  9/30/2022 23:55   10/1/2022 0:05
431275  655DB59D867FF74D  electric_bike  9/30/2022 23:57   10/1/2022 0:04
431276  3B82B03797EBB3D8   classic_bike  9/30/2022 23:57   10/1/2022 0:03
431277  88722C2C92791599   classic_bike  9/30/2022 23:58   10/1/2022 0:03
431278  B8BABCDA996F84C7   classic_bike  9/30/2022 23:59   10/1/2022 0:07

                             start_station_name start_station_id  \
0                            Marshall St & 2 St            HB408
1                            Marshall St & 2 St            HB408
2                            Marshall St & 2 St            HB408
3                            Marshall St & 2 St            HB408
4                            Marshall St & 2 St            HB408
...                                         ...              ...
431274  Hoboken Terminal - River St & Hudson Pl            HB102
431275  Hoboken Terminal - River St & Hudson Pl            HB102
431276                     12 St & Sinatra Dr N            HB201
431277                     12 St & Sinatra Dr N            HB201
431278  Hoboken Terminal - River St & Hudson Pl            HB102

                                  end_station_name end_station_id  start_lat  \
0                             8 St & Washington St          HB603  40.740802
1                            11 St & Washington St          HB502  40.740802
2                                      Oakland Ave          JC022  40.740802
3                            Bloomfield St & 15 St          HB203  40.740802
4                                Clinton St & 7 St          HB303  40.740802
...                                            ...            ...        ...
431274                        8 St & Washington St          HB603  40.736068
431275                        8 St & Washington St          HB603  40.736068
431276                        12 St & Sinatra Dr N          HB201  40.750604
431277                        12 St & Sinatra Dr N          HB201  40.750604
431278  Southwest Park - Jackson St & Observer Hwy          HB401  40.736068

        start_lng    end_lat    end_lng member_casual
0      -74.042521  40.745984 -74.028199        member
1      -74.042521  40.749985 -74.027150        casual
2      -74.042521  40.737604 -74.052478        member
3      -74.042521  40.754530 -74.026580        member
4      -74.042521  40.745420 -74.033320        casual
...           ...        ...        ...           ...
431274 -74.029127  40.745984 -74.028199        casual
431275 -74.029127  40.745984 -74.028199        casual
431276 -74.024020  40.750604 -74.024020        casual
431277 -74.024020  40.750604 -74.024020        casual
431278 -74.029127  40.737551 -74.041664        casual

[431279 rows x 13 columns]

In [8]:
total_df.to_csv('TotalDf.csv', index= False)

In [ ]:
total_weekends